/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class App {
    public static void main(String[] args) {
        NormalDuck normalDuck = new NormalDuck();
        normalDuck.display();
        normalDuck.fly();
        normalDuck.quack();

        JetPackDuck jetPackDuck = new JetPackDuck();
        jetPackDuck.display();
        jetPackDuck.fly();
        jetPackDuck.quack();

    }
}
